### ISSUE TITLE
Need binmode $fhandle

### ISSUE THREAD

**Issue by GabeSJones** [maurerpe/stock-flash#1]
https://github.com/maurerpe/stock-flash/blob/04193f6eeddeef8c344f2b33139ca40c3a24cc35/stock-flash.pl#L106

Putting the file handle into binary mode with

   binmode $fhandle;

will allow this script to work properly on Windows.

**Comment by maurerpe** [comment]
Fixed in commit 12598d2de2e44e845f0a1bfe0a2aeb5178865502

Thank you for this contribution.
